In [15]:
import numpy as np
import math
r = 25
array = np.array(shape=(5,1))

In [35]:
len(ans)

5

In [41]:
start = np.arange(1, 25)
start

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25])]

In [99]:
def print_pattern(r):
    rows, cols = int(math.floor(math.sqrt(r))), int(math.floor(math.sqrt(r)))
    small_ans = np.zeros((rows, cols))
    final = []
    start = np.arange(1, r+1)
    intermed_ans = [start[i:i+rows] for i in range(0, len(start), rows)]
    for idx, _ in enumerate(intermed_ans):
        if (idx+1) % 2 == 0:
            final.append(intermed_ans[idx][::-1])
        else:
            final.append(intermed_ans[idx])
    ans = np.array(final).transpose()
    row, col = ans.shape
    for i in range(row):
        for j in range(col):
            print(ans[i][j], end=' ')
        print(' ')

In [100]:
n = 256
print_pattern(n)

1 32 33 64 65 96 97 128 129 160 161 192 193 224 225 256  
2 31 34 63 66 95 98 127 130 159 162 191 194 223 226 255  
3 30 35 62 67 94 99 126 131 158 163 190 195 222 227 254  
4 29 36 61 68 93 100 125 132 157 164 189 196 221 228 253  
5 28 37 60 69 92 101 124 133 156 165 188 197 220 229 252  
6 27 38 59 70 91 102 123 134 155 166 187 198 219 230 251  
7 26 39 58 71 90 103 122 135 154 167 186 199 218 231 250  
8 25 40 57 72 89 104 121 136 153 168 185 200 217 232 249  
9 24 41 56 73 88 105 120 137 152 169 184 201 216 233 248  
10 23 42 55 74 87 106 119 138 151 170 183 202 215 234 247  
11 22 43 54 75 86 107 118 139 150 171 182 203 214 235 246  
12 21 44 53 76 85 108 117 140 149 172 181 204 213 236 245  
13 20 45 52 77 84 109 116 141 148 173 180 205 212 237 244  
14 19 46 51 78 83 110 115 142 147 174 179 206 211 238 243  
15 18 47 50 79 82 111 114 143 146 175 178 207 210 239 242  
16 17 48 49 80 81 112 113 144 145 176 177 208 209 240 241  
